version: "3.8"

services:
  lambda-fastapi-prod:
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    image: 358152105115.dkr.ecr.eu-west-2.amazonaws.com/serverless-webhook-listener:latest
    container_name: lambda-fastapi-prod
    ports:
      - 9000:8080

  lambda-fastapi-dev:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    env_file:
      - ./.env
    image: lambda-fastapi-dev:latest
    container_name: lambda-fastapi-dev
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 8001:8000